
source('annualGenerate.R')

annualplotTab <- tabItem(
  tabName='annualplot',
  fluidRow(
    box(width=4,
      h2('Activity'),
      'Add activity description here', br(),
      h2('Data Filters'),
      multiInput(inputId='species_annual',
                 label='Select Species (1-5 species):',
                 choices=levels(ss_data$Species),
                 selected=c('aardvark', 'aardwolf', 'baboon', 'buffalo')),
      selectInput(inputId = "y_annual", 
                  label = "y-axis", 
                  choices = c("Count", "Frequency")),
      switchInput(inputId='advanced_options_selected_annual',
                  label='Show Advanced options',
                  value=FALSE),
      conditionalPanel(condition='input.advanced_options_selected_annual == true',
                       checkboxGroupInput(inputId = "standing_annual",
                                          label = "Standing",
                                          choices = levels(ss_data$Standing),
                                          selected = c("Not standing", "Standing")),
                       checkboxGroupInput(inputId = "resting_annual",
                                          label = "Resting",
                                          choices = levels(ss_data$Resting),
                                          selected = c("Not resting", "Resting")),
                       checkboxGroupInput(inputId = "moving_annual",
                                          label = "Moving",
                                          choices = levels(ss_data$Moving),
                                          selected = c("Not moving", "Moving")),
                       checkboxGroupInput(inputId = "eating_annual",
                                          label = "Eating",
                                          choices = levels(ss_data$Eating),
                                          selected = c("Not eating", "Eating")),
                       checkboxGroupInput(inputId = "interacting_annual",
                                          label = "Interacting",
                                          choices = levels(ss_data$Interacting),
                                          selected = c("Not interacting", "Interacting")),
                       checkboxGroupInput(inputId = "babies_annual",
                                          label = "Babies",
                                          choices = levels(ss_data$Babies),
                                          selected = c("No babies", "Babies")),
                       checkboxGroupInput(inputId ="habitat_annual",
                                          label = "Habitat (select any or all)",
                                          choices = levels(ss_data$Habitat),
                                          selected = c("Dense Woodland",
                                                       "Grassland w/Trees",
                                                       "Open Grassland",
                                                       "Open Woodland/Shrubs")),
                       dateRangeInput(inputId ="date_annual",
                                      label = "Select date range",
                                      start  = min(ss_data$Date),
                                      end    = max(ss_data$Date),
                                      min    = min(ss_data$Date),
                                      max    = max(ss_data$Date),
                                      format = "mm/dd/yy",
                                      separator = " - ")
                       )
    ),
    box(width=8,
      h2('Output:'),
      plotOutput('annualplotRender')
    )
  )
)