
source('barGenerate.R')

barTab <- tabItem(
  tabName = 'barplot',
  fluidRow(
    box(width=4,
      h2('Activity:'),
      'Enter activity data here', br(),
      h2('Data Filters'),
      selectInput(inputId = "x_bar", 
                  label = "x-axis", 
                  choices = categorical_vars,
                  selected = "Babies"),
      selectInput(inputId = "y_bar", 
                  label = "y-axis", 
                  choices = c("Count", "Frequency"),
                  selected = "Count"),
      multiInput(inputId = "species_bar", 
                 label = "Species (select up to five)", 
                 choices = levels(ss_data$Species),
                 selected = c("aardvark")),
      switchInput(inputId='advanced_options_selected_bar',
                  label='Show Advanced options',
                  value=FALSE),
      conditionalPanel(condition='input.advanced_options_selected_bar == true',
                       checkboxGroupInput(inputId = "standing_bar",
                                          label = "Standing",
                                          choices = levels(ss_data$Standing),
                                          selected = c("Not standing", "Standing")),
                       checkboxGroupInput(inputId = "resting_bar",
                                          label = "Resting",
                                          choices = levels(ss_data$Resting),
                                          selected = c("Not resting", "Resting")),
                       checkboxGroupInput(inputId = "moving_bar",
                                          label = "Moving",
                                          choices = levels(ss_data$Moving),
                                          selected = c("Not moving", "Moving")),
                       checkboxGroupInput(inputId = "eating_bar",
                                          label = "Eating",
                                          choices = levels(ss_data$Eating),
                                          selected = c("Not eating", "Eating")),
                       checkboxGroupInput(inputId = "interacting_bar",
                                          label = "Interacting",
                                          choices = levels(ss_data$Interacting),
                                          selected = c("Not interacting", "Interacting")),
                       checkboxGroupInput(inputId = "babies_bar",
                                          label = "Babies",
                                          choices = levels(ss_data$Babies),
                                          selected = c("No babies", "Babies")),
                       checkboxGroupInput(inputId ="habitat_bar",
                                          label = "Habitat (select any or all)",
                                          choices = levels(ss_data$Habitat),
                                          selected = c("Dense Woodland",
                                                       "Grassland w/Trees",
                                                       "Open Grassland",
                                                       "Open Woodland/Shrubs")),
                       dateRangeInput(inputId ="date_bar",
                                      label = "Select date range",
                                      start  = min(ss_data$Date),
                                      end    = max(ss_data$Date),
                                      min    = min(ss_data$Date),
                                      max    = max(ss_data$Date),
                                      format = "mm/dd/yy",
                                      separator = " - "))
      
    ),
    box(width=8,
      h2('Output:'),
      plotOutput('barplotRender'),
      downloadButton('barDownload', 'Download')
    )
  )
)