
source('histoGenerate.R')

histoTab <- tabItem(
  tabName='histoplot',
  fluidRow(
    box(width=4,
      h2('Activity:'),
      'Enter activity description', br(),
      h2('Data Filters:'),
      selectInput(inputId = "x_histo", 
                  label = "x-axis", 
                  choices = continuous_vars,
                  selected = "Distance_to_River_m"),
      multiInput(inputId = "species_histo", 
                 label = "Species (select up to five)", 
                 choices = levels(ss_data$Species),
                 selected = c("aardvark")),
      switchInput(inputId='advanced_options_selected_histo',
                  label='Show Advanced options',
                  value=FALSE),
      conditionalPanel(condition='input.advanced_options_selected_histo == true',
                       checkboxGroupInput(inputId = "standing_histo",
                                          label = "Standing",
                                          choices = levels(ss_data$Standing),
                                          selected = c("Not standing", "Standing")),
                       checkboxGroupInput(inputId = "resting_histo",
                                          label = "Resting",
                                          choices = levels(ss_data$Resting),
                                          selected = c("Not resting", "Resting")),
                       checkboxGroupInput(inputId = "moving_histo",
                                          label = "Moving",
                                          choices = levels(ss_data$Moving),
                                          selected = c("Not moving", "Moving")),
                       checkboxGroupInput(inputId = "eating_histo",
                                          label = "Eating",
                                          choices = levels(ss_data$Eating),
                                          selected = c("Not eating", "Eating")),
                       checkboxGroupInput(inputId = "interacting_histo",
                                          label = "Interacting",
                                          choices = levels(ss_data$Interacting),
                                          selected = c("Not interacting", "Interacting")),
                       checkboxGroupInput(inputId = "babies_histo",
                                          label = "Babies",
                                          choices = levels(ss_data$Babies),
                                          selected = c("No babies", "Babies")),
                       checkboxGroupInput(inputId ="habitat_histo",
                                          label = "Habitat (select any or all)",
                                          choices = levels(ss_data$Habitat),
                                          selected = c("Dense Woodland",
                                                       "Grassland w/Trees",
                                                       "Open Grassland",
                                                       "Open Woodland/Shrubs")),
                       dateRangeInput(inputId ="date_histo",
                                      label = "Select date range",
                                      start  = min(ss_data$Date),
                                      end    = max(ss_data$Date),
                                      min    = min(ss_data$Date),
                                      max    = max(ss_data$Date),
                                      format = "mm/dd/yy",
                                      separator = " - "))
    ),
    box(width=8,
        h2('Output:'),
        plotOutput('histoplotRender')
    )
  )
)