
source('violinGenerate.R')

# violinplot tab
violinplotTab <- tabItem(
  tabName = 'violinplot',
  
  # Row for activity description and for data filters
  fluidRow(
    box(width=4,
      h2('Activity:'),
      'Filter using 1 variable', br(),
      'Filter using 2 variables', br(),
      '...tests', br(),
      h2('Data Filters:'),
      multiInput(inputId='species_violin',
                 label='Select Species (1-5 species):',
                 choices=levels(ss_data$Species),
                 selected=c('aardvark', 'aardwolf', 'baboon', 'buffalo')),
      switchInput(inputId='advanced_options_selected_violin',
                  label='Show Advanced options',
                  value=FALSE),
      conditionalPanel(condition='input.advanced_options_selected_violin == true',
                       checkboxGroupInput(inputId = "standing_violin",
                                          label = "Standing",
                                          choices = levels(ss_data$Standing),
                                          selected = c("Not standing", "Standing")),
                       checkboxGroupInput(inputId = "resting_violin",
                                          label = "Resting",
                                          choices = levels(ss_data$Resting),
                                          selected = c("Not resting", "Resting")),
                       checkboxGroupInput(inputId = "moving_violin",
                                          label = "Moving",
                                          choices = levels(ss_data$Moving),
                                          selected = c("Not moving", "Moving")),
                       checkboxGroupInput(inputId = "eating_violin",
                                          label = "Eating",
                                          choices = levels(ss_data$Eating),
                                          selected = c("Not eating", "Eating")),
                       checkboxGroupInput(inputId = "interacting_violin",
                                          label = "Interacting",
                                          choices = levels(ss_data$Interacting),
                                          selected = c("Not interacting", "Interacting")),
                       checkboxGroupInput(inputId = "babies_violin",
                                          label = "Babies",
                                          choices = levels(ss_data$Babies),
                                          selected = c("No babies", "Babies")),
                       checkboxGroupInput(inputId ="habitat_violin",
                                          label = "Habitat (select any or all)",
                                          choices = levels(ss_data$Habitat),
                                          selected = c("Dense Woodland",
                                                       "Grassland w/Trees",
                                                       "Open Grassland",
                                                       "Open Woodland/Shrubs")),
                       dateRangeInput(inputId ="date_violin",
                                      label = "Select date range",
                                      start  = min(ss_data$Date),
                                      end    = max(ss_data$Date),
                                      min    = min(ss_data$Date),
                                      max    = max(ss_data$Date),
                                      format = "mm/dd/yy",
                                      separator = " - "))),
    box(width=8,
        h2('Output:'),
        plotOutput('violinplotRender'),
        downloadButton('violinDownload', 'Download')
    )
  )
)
